[package]
name = "sembra-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
sembra-types = { version = "0.1.0", path = "../sembra-types" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
async-trait = "0.1"
sembra-storage = { path = "../sembra-storage" }
sembra-cache = { path = "../sembra-cache" }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
